/*
 *     Copyright 2026, Christopher Alan Mosher, New York, New York, USA, <cmosher01@gmail.com>.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* generated by Gemini AI with my prompting */

package nu.mine.mosher.zoom.neo4jgraphstream;

import lombok.val;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.DefaultView;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.view.ViewerListener;
import org.graphstream.ui.view.ViewerPipe;
import org.neo4j.driver.*;

import javax.swing.*;
import java.awt.*;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

// TODO see tutorial: https://graphstream-project.org/doc/Tutorials/Graph-Visualisation/

public class Neo4jGraphApplication {
    private static final String NEO4J_URI = "bolt://localhost:7687";
    private static final String NEO4J_USER = "neo4j";
    private static final String NEO4J_PASSWORD = "MarryCavalierLevitateGigahertz";

    private final Driver driver;
    private final Graph graph;

    public Neo4jGraphApplication() {
        // 1. Initialize Neo4j Driver Connection
        this.driver = GraphDatabase.driver(NEO4J_URI, AuthTokens.basic(NEO4J_USER, NEO4J_PASSWORD));

        // 2. Initialize GraphStream Graph Model
        System.setProperty("org.graphstream.ui", "swing");
        this.graph = new SingleGraph("Neo4jSlidingViewport");

        // Fast raw styling (Bypassing heavy rendering attributes to prioritize raw throughput)
        this.graph.removeAttribute("ui.quality");
        this.graph.removeAttribute("ui.antialias");
        this.graph.setAttribute("ui.stylesheet",
            "node { size: 15px; fill-color: #4CAF50; text-size: 12px; text-mode: normal; text-background-mode: rounded-box; text-background-color: white; }" +
                "node.clicked { fill-color: #FF5722; }" +
                "edge { fill-color: #9E9E9E; stroke-width: 1px; }"
        );
    }

    public void createAndShowGUI() {
        JFrame frame = new JFrame("Neo4j 1M-Node Sliding Viewport Application");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1024, 768);
        frame.setLayout(new BorderLayout());

        // 3. Set up the GraphStream Threaded Viewer and Component
        SwingViewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        DefaultView view = (DefaultView) viewer.addDefaultView(false);

        frame.add(view, BorderLayout.CENTER);

        // 4. Register the Custom Mouse Event Pipeline Listener
        ViewerPipe viewerPipe = viewer.newViewerPipe();
        viewerPipe.addViewerListener(new GraphNodeClickListener(graph, driver));

        // Pump UI interactions from the viewer queue at 50ms intervals
        new javax.swing.Timer(50, e -> {
            viewerPipe.pump();
        }).start();

        frame.setVisible(true);

        // TODO Initial Seed: Load a starting node to act as the viewport base
        // Replace "SeedNodeID" with a valid property ID value present inside your database
        loadInitialNode("4:5c720bd2-a679-479b-90ee-93d0160cc211:3");
    }

    private void loadInitialNode(String seedId) {
        if (graph.getNode(seedId) == null) {
            Node seedNode = graph.addNode(seedId);
            seedNode.setAttribute("ui.label", seedId);
        }
    }

    public void shutdown() {
        if (driver != null) {
            driver.close();
        }
    }

    public static void main(String[] args) {
        System.setProperty("sun.java2d.uiScale", "100%");
        SwingUtilities.invokeLater(() -> {
            Neo4jGraphApplication app = new Neo4jGraphApplication();
            app.createAndShowGUI();

            // Graceful driver termination hook
            Runtime.getRuntime().addShutdownHook(new Thread(app::shutdown));
        });
    }

    // --- INNER CLASS: ASYNCHRONOUS GRAPH EXPLORATION CONTROLLER ---
    private static class GraphNodeClickListener implements ViewerListener {
        private final Graph visualGraph;
        private final Driver neo4jDriver;
        private static final int DISP_LIMIT = 500; // Limits layout calculations per click
        private static final int MAX_CANVAS_NODES = 5000; // Rolling threshold constraint

        public GraphNodeClickListener(Graph visualGraph, Driver neo4jDriver) {
            this.visualGraph = visualGraph;
            this.neo4jDriver = neo4jDriver;
        }

        @Override
        public void viewClosed(String viewName) {}

        @Override
        public void buttonPushed(String id) {
            // Asynchronously process Neo4j database calls off the EDT thread
            CompletableFuture.runAsync(() -> {
                String cypher =
//                    "MATCH (c {id: $id})-[r]-(n) " +
//                        "RETURN c.id as source, n.id as target " +
//                        "LIMIT $limit";
                "MATCH (c)-[r]-(n) WHERE elementId(c) = $id RETURN elementId(c) as source, elementId(n) as target LIMIT $limit";
// TODO Do we need to account for: (c)-[r]->(n) vs. (c)<-[r]-(n)
                try (Session session = neo4jDriver.session()) {
                    session.run(cypher, Map.of("id", id, "limit", DISP_LIMIT))
                        .forEachRemaining(record -> {
                            String src = record.get("source").asString();
                            String tgt = record.get("target").asString();
                            String edgeKey = src + "->" + tgt;

                            // UI mutation context block executed back inside the Swing thread safe loop
                            SwingUtilities.invokeLater(() -> {
                                if (visualGraph.getNode(src) == null) {
                                    Node n = visualGraph.addNode(src);
                                    n.setAttribute("ui.label", src);
                                }
                                if (visualGraph.getNode(tgt) == null) {
                                    Node n = visualGraph.addNode(tgt);
                                    n.setAttribute("ui.label", tgt);
                                }
                                if (visualGraph.getEdge(edgeKey) == null) {
                                    visualGraph.addEdge(edgeKey, src, tgt);
                                    // TODO causes errors like the following (maybe because the code needs to account for directed edges from neo4j???)
/*
Exception in thread "AWT-EventQueue-0" org.graphstream.graph.EdgeRejectedException: Edge 4:5c720bd2-a679-479b-90ee-93d0160cc211:4->4:5c720bd2-a679-479b-90ee-93d0160cc211:3[4:5c720bd2-a679-479b-90ee-93d0160cc211:4--4:5c720bd2-a679-479b-90ee-93d0160cc211:3] was rejected by node 4:5c720bd2-a679-479b-90ee-93d0160cc211:4
    at org.graphstream.graph.implementations.AbstractGraph.addEdge(AbstractGraph.java:605)
    at org.graphstream.graph.implementations.AbstractGraph.addEdge(AbstractGraph.java:262)
    at org.graphstream.graph.Graph.addEdge(Graph.java:422)
    at org.graphstream.graph.Graph.addEdge(Graph.java:375)
    at nu.mine.mosher.zoom.neo4jgraphstream.Neo4jGraphApplication$GraphNodeClickListener.lambda$buttonPushed$0(Neo4jGraphApplication.java:161)
*/
                                }

                                // Mark active cluster node visually
                                Node clicked = visualGraph.getNode(id);
                                if (clicked != null) clicked.setAttribute("ui.class", "clicked");

                                // Enforce rolling memory buffer pruning if size matches threshold boundaries
                                if (visualGraph.getNodeCount() > MAX_CANVAS_NODES) {
                                    Node oldNode = visualGraph.getNode(0);
                                    if (oldNode != null && !oldNode.getId().equals(id)) {
                                        visualGraph.removeNode(oldNode);
                                    }
                                }
                            });
                        });
                }
            }).exceptionally(ex -> {
                ex.printStackTrace();
                return null;
            });
        }

        // TODO
        public void buttonPushed_TODO_TRY_THIS(String id) {
            val graph = visualGraph;
            Node clickedNode = graph.getNode(id);
            if (clickedNode == null) return;

            // 1. Look at all incoming edges (e.g., From NodeB -> ClickedNode)
            clickedNode.enteringEdges().forEach(incomingEdge -> {
                Node sourceNode = incomingEdge.getSourceNode();

                // We want to add a reverse edge: ClickedNode -> NodeB
                String newEdgeId = clickedNode.getId() + "_to_" + sourceNode.getId();

                // Safety check to prevent "Edge rejected" crashes
                if (graph.getEdge(newEdgeId) == null) {
                    graph.addEdge(newEdgeId, clickedNode.getId(), sourceNode.getId(), true);
                }
            });

            // 2. Look at all outgoing edges (e.g., ClickedNode -> NodeC)
            clickedNode.leavingEdges().forEach(outgoingEdge -> {
                Node targetNode = outgoingEdge.getTargetNode();

                // We want to add a reverse edge: NodeC -> ClickedNode
                String newEdgeId = targetNode.getId() + "_to_" + clickedNode.getId();

                if (graph.getEdge(newEdgeId) == null) {
                    graph.addEdge(newEdgeId, targetNode.getId(), clickedNode.getId(), true);
                }
            });
        }

        @Override
        public void buttonReleased(String id) {}

        @Override
        public void mouseOver(String id) {
            System.out.println("mouseover");
        }

        @Override
        public void mouseLeft(String id) {}
    }
}
